spring:
  redis:
    host: 127.0.0.1
    password: rd0U.p57RqZ!7e
    database: 15
  datasource:
    url: jdbc:mysql://5628e0ad1c559.sh.cdb.myqcloud.com:9993/virgo?useSSL=true&serverTimezone=GMT%2B8
    username: cdb_outerroot
    password: Vsl88402_uuY6
    driver-class-name: com.mysql.cj.jdbc.Driver
  boot:
    admin:
      client:
        url: http://141.164.49.58:8866
        instance:
          prefer-ip: true
          service-url: http://123.56.7.121:8000
management:
  endpoints:
    web:
      exposure:
        include: "*"
app:
  sms:
    type: aliyun