spring:
  redis:
    host: 123.56.7.121
    password: rd0U.p57RqZ!7e
    database: 11
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/virgo?useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: qwe123
    driver-class-name: com.mysql.cj.jdbc.Driver
  boot:
    admin:
      client:
        url: http://123.56.7.121:8866
        instance:
          prefer-ip: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
app:
  sms:
    type: aliyun