spring:
  redis:
    host: 123.56.7.121
    password: rd0U.p57RqZ!7e
    database: 11
  datasource:
    url: jdbc:mysql://5628e0ad1c559.sh.cdb.myqcloud.com:9993/demo-test?useSSL=true&serverTimezone=GMT%2B8
    username: cdb_outerroot
    password: Vsl88402_uuY6
    driver-class-name: com.mysql.cj.jdbc.Driver
  boot:
    admin:
      client:
        url: http://123.56.7.121:8866
        instance:
          prefer-ip: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
app:
  sms:
    type: aliyun