spring:
  profiles:
    active: '@env@'
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: api
          uri: http://127.0.0.1:8001
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
            - Api
        - id: adminApi
          uri: http://127.0.0.1:8002
          predicates:
            - Path=/admin/api/**
          filters:
            - StripPrefix=2
            - Api
        - id: devApp
          uri: http://2308813f.nat123.cc:24079
          predicates:
            - Path=/dev/api/**
          filters:
            - StripPrefix=2
            - Api
        - id: devAdmin
          uri: http://480cbfeb.nat123.fun:24085
          predicates:
            - Path=/devadmin/api/**
          filters:
            - StripPrefix=2
            - Api
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 8000
logging:
  file:
    path: ./logs/gateway